version: '2.4'
services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - '8000:80'
      - '9229:9229' # for debugging
    volumes:
      - .:/usr/src/app:rw,Z
      - /usr/src/app/node_modules
    networks:
      - bridge
